spring.application.name=bytemates

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.sewufviqicgrilplspfk
spring.datasource.password=Ferrater_24

# Fix for prepared statement errors with Supabase
spring.datasource.hikari.data-source-properties.preparedStatementCacheQueries=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheSize=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheSqlLimit=0
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8080

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.example.bytemates=DEBUG